# Generated by Django 6.0.7 on 2026-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_movies_date_added_alter_movies_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
