# Generated by Django 6.0.7 on 2026-07-17

from django.db import migrations


def seed_genres(apps, schema_editor):
    Genre = apps.get_model('myApp', 'Genre')
    default_genres = [
        'Action',
        'Comedy',
        'Drama',
        'Horror',
        'Romance',
        'Sci-Fi',
        'Thriller',
        'Animation',
        'Documentary',
        'Fantasy',
        'Mystery',
        'Musical',
        'War',
        'Western',
    ]

    for name in default_genres:
        Genre.objects.get_or_create(name=name)


def unseed_genres(apps, schema_editor):
    Genre = apps.get_model('myApp', 'Genre')
    Genre.objects.filter(
        name__in=[
            'Action',
            'Comedy',
            'Drama',
            'Horror',
            'Romance',
            'Sci-Fi',
            'Thriller',
            'Animation',
            'Documentary',
            'Fantasy',
            'Mystery',
            'Musical',
            'War',
            'Western',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_genre_remove_movies_genre_movies_genres'),
    ]

    operations = [
        migrations.RunPython(seed_genres, unseed_genres),
    ]
