# Generated by Django 6.0.7 on 2026-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_seed_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
