# Generated by Django 6.0.7 on 2026-07-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_movies_screenshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='screenshots',
        ),
    ]
