# Generated by Django 6.0.7 on 2026-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_remove_movies_screenshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="movies",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
