# Generated by Django 6.0.7 on 2026-08-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0008_movies_rating_movies_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="trailer_link",
            field=models.URLField(blank=True),
        ),
    ]
